= Gatsby blog dev from scratch

Base of all is article https://www.freecodecamp.org/news/build-a-developer-blog-from-scratch-with-gatsby-and-mdx/


== HOW TO

=== How to get to Gatsby GraphQL?

After `yarn dev` the site is accessible at
http://localhost:9988
then the GraphQL query processor at http://localhost:9988/___graphql

Testing graphql for Markdown and Asciidoctor

[source,graphql]
====
{
  allAsciidoc {
    edges {
      node {
        html
        document {
          title
          subtitle
          main
        }
        revision {
          date
          number
        }
        pageAttributes {
          title
          path
          category
        }
      }
    }
  }
  allMdx {
    nodes {
      frontmatter {
        title
        published
        date
      }
      excerpt(pruneLength: 250)
    }
  }
  site {
    siteMetadata {
      title
      description
    }
  }
}
====

For example I cannot find the `excerpt` from Markdown
but it could be probably substituted with explicit definition of like `page-synopsis`
and use of `pageAttributes`.  

=== How to add Asciidoctor support?

Work with
https://www.gatsbyjs.com/plugins/gatsby-transformer-asciidoc/

The configuration options for the plugin can be found at
https://docs.asciidoctor.org/asciidoctor.js/latest/processor/convert-options/
and options
https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/

[source,sh]
----
# 1) configure the plugin
yarn add gatsby-transformer-asciidoc

# 2) add the plugin declaration (with configuration) into gatsby-config.js

# 3) create the `adoc` file under the `/post` directory
# (where the files are expected is configured with gatsby-source-filesystem plugin)
----

=== GraphQL queries from Markdown to Asciidoctor

[source,graphql]
====
{
  allMdx(
    sort: { fields: [frontmatter___date], order: DESC }
    filter: { frontmatter: { published: { eq: true } } }
  ) {
    nodes {
      id
      excerpt(pruneLength: 250)
      frontmatter {
        title
        date
      }
    }
  }
  allAsciidoc(
    sort: { fields: [revision___date], order: DESC }
    filter: { pageAttributes: { published: { eq: "true" } } }
  ) {
    edges {
      node {
        id
        document {
          title
        }
        pageAttributes {
		  synopsis
        }
        revision {
          date
        }
      }
    }
  }
}
====

=== To build

[source,sh]
----
# gatsby build --prefix-paths
yarn build
----

Result can be found at `public/`.

=== To work with github pages

See https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/

[source,sh]
----
# --> yarn add gh-pages
yarn deploy
----